"""FROZEN budget-pressure set at scale (pressure2, 2026-10-08). DO NOT EDIT; add a new set instead.

Question: does a CLAUDE.md holding EVERY memory start dropping rules as it grows, where per-prompt retrieval does not?
4 arbitrary conventions x 2 sizes: s300 (~24k chars of CLAUDE.md) and s1200 (~95k chars, ~24k tokens).
Fixes over pressure1: distractor rules live only in ~150 synthetic directories that never overlap a target
directory, and each trap judges only the exact file the task asks for.
Arms: nomem, claudemd_full, memcode_retrieval (pinned-only is settled by pressure1: it fails like nomem).

Pre-registered, deterministic predictions (offline_check at the freezing commit): the target is never in the pinned
block; retrieval injects exactly one memory, the target, in all 8 variants. So memcode_retrieval should match the
s300 CLAUDE.md arm; the open question is whether claudemd_full degrades at s1200.
Selection: every scenario failed 6/6 without memory and 0/4 with the rule in the prompt (oracle).
tests/test_heldout_frozen.py enforces the hash below.
"""
import json

PRESSURE2 = json.loads(r"""[
 {
  "files": {
   "README.md": "Demo service.\n",
   "api/__init__.py": "",
   "api/errors.py": "class ApiError(Exception):\n    pass\n\n\ndef fail(code, msg):\n    raise ApiError(code, msg)\n",
   "api/users.py": "USERS = {}\n",
   "billing/__init__.py": "",
   "billing/invoice.py": "def total_cents(items):\n    return sum(i['cents'] for i in items)\n",
   "data/etl.py": "def run():\n    pass\n",
   "docs/index.md": "# Docs\n",
   "frontend/app.js": "export const app = {};\n",
   "infra/deploy.sh": "#!/bin/sh\n",
   "ledger/__init__.py": "",
   "ledger/entries.py": "ENTRIES = []\n",
   "mobile/App.kt": "class App\n",
   "queue/__init__.py": "",
   "queue/worker.py": "def run(job):\n    return job()\n",
   "reports/__init__.py": "",
   "reports/weekly.py": "",
   "scripts/release.sh": "#!/bin/sh\n",
   "search/__init__.py": "",
   "search/index.py": "def tokens(text):\n    return text.split()\n",
   "tools/__init__.py": "",
   "tools/sync.py": "import argparse\n\n\ndef main():\n    p = argparse.ArgumentParser()\n    p.add_argument('src')\n    return p.parse_args()\n",
   "util/__init__.py": "",
   "util/dates.py": "import datetime\n",
   "worker/__init__.py": "",
   "worker/log.py": "import logging\n\n\ndef get(name):\n    return logging.getLogger('worker.' + name)\n"
  },
  "later": "Create billing/refunds.py with a function refund(amount_cents, reason) that returns a refund record.",
  "n_notes": 60,
  "n_rules": 240,
  "name": "billing_header_s300",
  "oracle": "Rule: every new module under billing/ starts with the exact line '# PCI-SCOPE'.",
  "target": [
   "correction",
   "Every new module under billing/ starts with the exact line '# PCI-SCOPE'.",
   ""
  ],
  "trap_on": "content",
  "trap_path": "(^|/)billing/refunds\\.py$",
  "trap_regex": "\\A(?!# PCI-SCOPE)",
  "tuned_on": false
 },
 {
  "files": {
   "README.md": "Demo service.\n",
   "api/__init__.py": "",
   "api/errors.py": "class ApiError(Exception):\n    pass\n\n\ndef fail(code, msg):\n    raise ApiError(code, msg)\n",
   "api/users.py": "USERS = {}\n",
   "billing/__init__.py": "",
   "billing/invoice.py": "def total_cents(items):\n    return sum(i['cents'] for i in items)\n",
   "data/etl.py": "def run():\n    pass\n",
   "docs/index.md": "# Docs\n",
   "frontend/app.js": "export const app = {};\n",
   "infra/deploy.sh": "#!/bin/sh\n",
   "ledger/__init__.py": "",
   "ledger/entries.py": "ENTRIES = []\n",
   "mobile/App.kt": "class App\n",
   "queue/__init__.py": "",
   "queue/worker.py": "def run(job):\n    return job()\n",
   "reports/__init__.py": "",
   "reports/weekly.py": "",
   "scripts/release.sh": "#!/bin/sh\n",
   "search/__init__.py": "",
   "search/index.py": "def tokens(text):\n    return text.split()\n",
   "tools/__init__.py": "",
   "tools/sync.py": "import argparse\n\n\ndef main():\n    p = argparse.ArgumentParser()\n    p.add_argument('src')\n    return p.parse_args()\n",
   "util/__init__.py": "",
   "util/dates.py": "import datetime\n",
   "worker/__init__.py": "",
   "worker/log.py": "import logging\n\n\ndef get(name):\n    return logging.getLogger('worker.' + name)\n"
  },
  "later": "Create billing/refunds.py with a function refund(amount_cents, reason) that returns a refund record.",
  "n_notes": 200,
  "n_rules": 1000,
  "name": "billing_header_s1200",
  "oracle": "Rule: every new module under billing/ starts with the exact line '# PCI-SCOPE'.",
  "target": [
   "correction",
   "Every new module under billing/ starts with the exact line '# PCI-SCOPE'.",
   ""
  ],
  "trap_on": "content",
  "trap_path": "(^|/)billing/refunds\\.py$",
  "trap_regex": "\\A(?!# PCI-SCOPE)",
  "tuned_on": false
 },
 {
  "files": {
   "README.md": "Demo service.\n",
   "api/__init__.py": "",
   "api/errors.py": "class ApiError(Exception):\n    pass\n\n\ndef fail(code, msg):\n    raise ApiError(code, msg)\n",
   "api/users.py": "USERS = {}\n",
   "billing/__init__.py": "",
   "billing/invoice.py": "def total_cents(items):\n    return sum(i['cents'] for i in items)\n",
   "data/etl.py": "def run():\n    pass\n",
   "docs/index.md": "# Docs\n",
   "frontend/app.js": "export const app = {};\n",
   "infra/deploy.sh": "#!/bin/sh\n",
   "ledger/__init__.py": "",
   "ledger/entries.py": "ENTRIES = []\n",
   "mobile/App.kt": "class App\n",
   "queue/__init__.py": "",
   "queue/worker.py": "def run(job):\n    return job()\n",
   "reports/__init__.py": "",
   "reports/weekly.py": "",
   "scripts/release.sh": "#!/bin/sh\n",
   "search/__init__.py": "",
   "search/index.py": "def tokens(text):\n    return text.split()\n",
   "tools/__init__.py": "",
   "tools/sync.py": "import argparse\n\n\ndef main():\n    p = argparse.ArgumentParser()\n    p.add_argument('src')\n    return p.parse_args()\n",
   "util/__init__.py": "",
   "util/dates.py": "import datetime\n",
   "worker/__init__.py": "",
   "worker/log.py": "import logging\n\n\ndef get(name):\n    return logging.getLogger('worker.' + name)\n"
  },
  "later": "Add an option to tools/sync.py that makes it skip writing any files (a dry run).",
  "n_notes": 60,
  "n_rules": 240,
  "name": "tools_flags_s300",
  "oracle": "Rule: command-line options in tools/ are one lowercase word without inner dashes, e.g. --dryrun.",
  "target": [
   "correction",
   "Command-line options in tools/ are spelled as one lowercase word without dashes inside, like --dryrun or --nocache.",
   ""
  ],
  "trap_on": "content",
  "trap_path": "(^|/)tools/sync\\.py$",
  "trap_regex": "--dry[-_]run",
  "tuned_on": false
 },
 {
  "files": {
   "README.md": "Demo service.\n",
   "api/__init__.py": "",
   "api/errors.py": "class ApiError(Exception):\n    pass\n\n\ndef fail(code, msg):\n    raise ApiError(code, msg)\n",
   "api/users.py": "USERS = {}\n",
   "billing/__init__.py": "",
   "billing/invoice.py": "def total_cents(items):\n    return sum(i['cents'] for i in items)\n",
   "data/etl.py": "def run():\n    pass\n",
   "docs/index.md": "# Docs\n",
   "frontend/app.js": "export const app = {};\n",
   "infra/deploy.sh": "#!/bin/sh\n",
   "ledger/__init__.py": "",
   "ledger/entries.py": "ENTRIES = []\n",
   "mobile/App.kt": "class App\n",
   "queue/__init__.py": "",
   "queue/worker.py": "def run(job):\n    return job()\n",
   "reports/__init__.py": "",
   "reports/weekly.py": "",
   "scripts/release.sh": "#!/bin/sh\n",
   "search/__init__.py": "",
   "search/index.py": "def tokens(text):\n    return text.split()\n",
   "tools/__init__.py": "",
   "tools/sync.py": "import argparse\n\n\ndef main():\n    p = argparse.ArgumentParser()\n    p.add_argument('src')\n    return p.parse_args()\n",
   "util/__init__.py": "",
   "util/dates.py": "import datetime\n",
   "worker/__init__.py": "",
   "worker/log.py": "import logging\n\n\ndef get(name):\n    return logging.getLogger('worker.' + name)\n"
  },
  "later": "Add an option to tools/sync.py that makes it skip writing any files (a dry run).",
  "n_notes": 200,
  "n_rules": 1000,
  "name": "tools_flags_s1200",
  "oracle": "Rule: command-line options in tools/ are one lowercase word without inner dashes, e.g. --dryrun.",
  "target": [
   "correction",
   "Command-line options in tools/ are spelled as one lowercase word without dashes inside, like --dryrun or --nocache.",
   ""
  ],
  "trap_on": "content",
  "trap_path": "(^|/)tools/sync\\.py$",
  "trap_regex": "--dry[-_]run",
  "tuned_on": false
 },
 {
  "files": {
   "README.md": "Demo service.\n",
   "api/__init__.py": "",
   "api/errors.py": "class ApiError(Exception):\n    pass\n\n\ndef fail(code, msg):\n    raise ApiError(code, msg)\n",
   "api/users.py": "USERS = {}\n",
   "billing/__init__.py": "",
   "billing/invoice.py": "def total_cents(items):\n    return sum(i['cents'] for i in items)\n",
   "data/etl.py": "def run():\n    pass\n",
   "docs/index.md": "# Docs\n",
   "frontend/app.js": "export const app = {};\n",
   "infra/deploy.sh": "#!/bin/sh\n",
   "ledger/__init__.py": "",
   "ledger/entries.py": "ENTRIES = []\n",
   "mobile/App.kt": "class App\n",
   "queue/__init__.py": "",
   "queue/worker.py": "def run(job):\n    return job()\n",
   "reports/__init__.py": "",
   "reports/weekly.py": "",
   "scripts/release.sh": "#!/bin/sh\n",
   "search/__init__.py": "",
   "search/index.py": "def tokens(text):\n    return text.split()\n",
   "tools/__init__.py": "",
   "tools/sync.py": "import argparse\n\n\ndef main():\n    p = argparse.ArgumentParser()\n    p.add_argument('src')\n    return p.parse_args()\n",
   "util/__init__.py": "",
   "util/dates.py": "import datetime\n",
   "worker/__init__.py": "",
   "worker/log.py": "import logging\n\n\ndef get(name):\n    return logging.getLogger('worker.' + name)\n"
  },
  "later": "Create queue/retry_policy.py with a function backoff(attempt) that returns the delay in seconds for a retry.",
  "n_notes": 60,
  "n_rules": 240,
  "name": "queue_version_s300",
  "oracle": "Rule: every new module under queue/ defines a module-level constant SCHEMA_VERSION = 2.",
  "target": [
   "correction",
   "Every new module under queue/ defines a module-level constant SCHEMA_VERSION = 2.",
   ""
  ],
  "trap_on": "content",
  "trap_path": "(^|/)queue/retry_policy\\.py$",
  "trap_regex": "\\A(?!.*SCHEMA_VERSION\\s*=\\s*2\\b)",
  "tuned_on": false
 },
 {
  "files": {
   "README.md": "Demo service.\n",
   "api/__init__.py": "",
   "api/errors.py": "class ApiError(Exception):\n    pass\n\n\ndef fail(code, msg):\n    raise ApiError(code, msg)\n",
   "api/users.py": "USERS = {}\n",
   "billing/__init__.py": "",
   "billing/invoice.py": "def total_cents(items):\n    return sum(i['cents'] for i in items)\n",
   "data/etl.py": "def run():\n    pass\n",
   "docs/index.md": "# Docs\n",
   "frontend/app.js": "export const app = {};\n",
   "infra/deploy.sh": "#!/bin/sh\n",
   "ledger/__init__.py": "",
   "ledger/entries.py": "ENTRIES = []\n",
   "mobile/App.kt": "class App\n",
   "queue/__init__.py": "",
   "queue/worker.py": "def run(job):\n    return job()\n",
   "reports/__init__.py": "",
   "reports/weekly.py": "",
   "scripts/release.sh": "#!/bin/sh\n",
   "search/__init__.py": "",
   "search/index.py": "def tokens(text):\n    return text.split()\n",
   "tools/__init__.py": "",
   "tools/sync.py": "import argparse\n\n\ndef main():\n    p = argparse.ArgumentParser()\n    p.add_argument('src')\n    return p.parse_args()\n",
   "util/__init__.py": "",
   "util/dates.py": "import datetime\n",
   "worker/__init__.py": "",
   "worker/log.py": "import logging\n\n\ndef get(name):\n    return logging.getLogger('worker.' + name)\n"
  },
  "later": "Create queue/retry_policy.py with a function backoff(attempt) that returns the delay in seconds for a retry.",
  "n_notes": 200,
  "n_rules": 1000,
  "name": "queue_version_s1200",
  "oracle": "Rule: every new module under queue/ defines a module-level constant SCHEMA_VERSION = 2.",
  "target": [
   "correction",
   "Every new module under queue/ defines a module-level constant SCHEMA_VERSION = 2.",
   ""
  ],
  "trap_on": "content",
  "trap_path": "(^|/)queue/retry_policy\\.py$",
  "trap_regex": "\\A(?!.*SCHEMA_VERSION\\s*=\\s*2\\b)",
  "tuned_on": false
 },
 {
  "files": {
   "README.md": "Demo service.\n",
   "api/__init__.py": "",
   "api/errors.py": "class ApiError(Exception):\n    pass\n\n\ndef fail(code, msg):\n    raise ApiError(code, msg)\n",
   "api/users.py": "USERS = {}\n",
   "billing/__init__.py": "",
   "billing/invoice.py": "def total_cents(items):\n    return sum(i['cents'] for i in items)\n",
   "data/etl.py": "def run():\n    pass\n",
   "docs/index.md": "# Docs\n",
   "frontend/app.js": "export const app = {};\n",
   "infra/deploy.sh": "#!/bin/sh\n",
   "ledger/__init__.py": "",
   "ledger/entries.py": "ENTRIES = []\n",
   "mobile/App.kt": "class App\n",
   "queue/__init__.py": "",
   "queue/worker.py": "def run(job):\n    return job()\n",
   "reports/__init__.py": "",
   "reports/weekly.py": "",
   "scripts/release.sh": "#!/bin/sh\n",
   "search/__init__.py": "",
   "search/index.py": "def tokens(text):\n    return text.split()\n",
   "tools/__init__.py": "",
   "tools/sync.py": "import argparse\n\n\ndef main():\n    p = argparse.ArgumentParser()\n    p.add_argument('src')\n    return p.parse_args()\n",
   "util/__init__.py": "",
   "util/dates.py": "import datetime\n",
   "worker/__init__.py": "",
   "worker/log.py": "import logging\n\n\ndef get(name):\n    return logging.getLogger('worker.' + name)\n"
  },
  "later": "Create ledger/balance.py with a function balance(entries) that sums the amount of each entry.",
  "n_notes": 60,
  "n_rules": 240,
  "name": "ledger_footer_s300",
  "oracle": "Rule: new modules under ledger/ end with the exact line '# end-of-ledger-module'.",
  "target": [
   "correction",
   "New modules under ledger/ end with the exact line '# end-of-ledger-module'.",
   ""
  ],
  "trap_on": "content",
  "trap_path": "(^|/)ledger/balance\\.py$",
  "trap_regex": "\\A(?!.*# end-of-ledger-module\\s*\\Z)",
  "tuned_on": false
 },
 {
  "files": {
   "README.md": "Demo service.\n",
   "api/__init__.py": "",
   "api/errors.py": "class ApiError(Exception):\n    pass\n\n\ndef fail(code, msg):\n    raise ApiError(code, msg)\n",
   "api/users.py": "USERS = {}\n",
   "billing/__init__.py": "",
   "billing/invoice.py": "def total_cents(items):\n    return sum(i['cents'] for i in items)\n",
   "data/etl.py": "def run():\n    pass\n",
   "docs/index.md": "# Docs\n",
   "frontend/app.js": "export const app = {};\n",
   "infra/deploy.sh": "#!/bin/sh\n",
   "ledger/__init__.py": "",
   "ledger/entries.py": "ENTRIES = []\n",
   "mobile/App.kt": "class App\n",
   "queue/__init__.py": "",
   "queue/worker.py": "def run(job):\n    return job()\n",
   "reports/__init__.py": "",
   "reports/weekly.py": "",
   "scripts/release.sh": "#!/bin/sh\n",
   "search/__init__.py": "",
   "search/index.py": "def tokens(text):\n    return text.split()\n",
   "tools/__init__.py": "",
   "tools/sync.py": "import argparse\n\n\ndef main():\n    p = argparse.ArgumentParser()\n    p.add_argument('src')\n    return p.parse_args()\n",
   "util/__init__.py": "",
   "util/dates.py": "import datetime\n",
   "worker/__init__.py": "",
   "worker/log.py": "import logging\n\n\ndef get(name):\n    return logging.getLogger('worker.' + name)\n"
  },
  "later": "Create ledger/balance.py with a function balance(entries) that sums the amount of each entry.",
  "n_notes": 200,
  "n_rules": 1000,
  "name": "ledger_footer_s1200",
  "oracle": "Rule: new modules under ledger/ end with the exact line '# end-of-ledger-module'.",
  "target": [
   "correction",
   "New modules under ledger/ end with the exact line '# end-of-ledger-module'.",
   ""
  ],
  "trap_on": "content",
  "trap_path": "(^|/)ledger/balance\\.py$",
  "trap_regex": "\\A(?!.*# end-of-ledger-module\\s*\\Z)",
  "tuned_on": false
 }
]""")

PREDICTIONS = json.loads(r"""{"billing_header_s1200": {"injected_relevance": 1, "injected_salience": 1, "memories": 1201, "rank_relevance": 0, "rank_salience": 0, "retrieved_relevance": true, "retrieved_salience": true, "target_pinned": false}, "billing_header_s300": {"injected_relevance": 1, "injected_salience": 1, "memories": 301, "rank_relevance": 0, "rank_salience": 0, "retrieved_relevance": true, "retrieved_salience": true, "target_pinned": false}, "ledger_footer_s1200": {"injected_relevance": 1, "injected_salience": 1, "memories": 1201, "rank_relevance": 0, "rank_salience": 0, "retrieved_relevance": true, "retrieved_salience": true, "target_pinned": false}, "ledger_footer_s300": {"injected_relevance": 1, "injected_salience": 1, "memories": 301, "rank_relevance": 0, "rank_salience": 0, "retrieved_relevance": true, "retrieved_salience": true, "target_pinned": false}, "queue_version_s1200": {"injected_relevance": 1, "injected_salience": 1, "memories": 1201, "rank_relevance": 0, "rank_salience": 0, "retrieved_relevance": true, "retrieved_salience": true, "target_pinned": false}, "queue_version_s300": {"injected_relevance": 1, "injected_salience": 1, "memories": 301, "rank_relevance": 0, "rank_salience": 0, "retrieved_relevance": true, "retrieved_salience": true, "target_pinned": false}, "tools_flags_s1200": {"injected_relevance": 1, "injected_salience": 1, "memories": 1201, "rank_relevance": 0, "rank_salience": 0, "retrieved_relevance": true, "retrieved_salience": true, "target_pinned": false}, "tools_flags_s300": {"injected_relevance": 1, "injected_salience": 1, "memories": 301, "rank_relevance": 0, "rank_salience": 0, "retrieved_relevance": true, "retrieved_salience": true, "target_pinned": false}}""")

FROZEN_SHA256 = "d58afc7b863cfbcf8f27a36bb8320bbb0226acd27f1e6f52b1c53c08ca9c0574"
